# Generated by Django 4.0.4 on 2023-09-21 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_bookinstance_borrower'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='birth_date',
            field=models.DateField(blank=True, default='', help_text='Введите дату рождения автора', null=True, verbose_name='Дата рождения автора'),
        ),
        migrations.AlterField(
            model_name='author',
            name='death_date',
            field=models.DateField(blank=True, default='', help_text='Введите дату смерти автора', null=True, verbose_name='Дата смерти автора'),
        ),
    ]
